topic:
  name: mytopic
  partitions-num: 6
  replication-factor: 3
server:
  port: 9080
spring:
  kafka:
    bootstrap-servers:
      - pkc-lzvrd.us-west4.gcp.confluent.cloud:9092  # <1>
    properties:
      # CCloud broker connection parameters 
      ssl.endpoint.identification.algorithm: https
      sasl.mechanism: PLAIN
      request.timeout.ms: 20000
      retry.backoff.ms: 500
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="4R5XNLOP466MQWQA" password="CiOuyecZiRlUoflD/RNLCQk+FvNrXSFRoFsZlCul1j8ZFwk7ayROXS0H8jfogpi5";  # <2>
      security.protocol: SASL_SSL

      # CCloud Schema Registry Connection parameter
      schema.registry.url: https://psrc-41vyv.australia-southeast1.gcp.confluent.cloud  # <3>
      basic.auth.credentials.source: USER_INFO  # <4>
      schema.registry.basic.auth.user.info: QSHSH5V47ZIHX3ZC:26bU1tSa3D7jOd7BphEn8vpaU15FwzDVv41Zup/P4Wr7lfO94Q6YCfL5DaQJ0Q0f # <5>
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    template:
      default-topic:
logging:
  level:
    root: info