server:
 port: 9090

       
security:
  oauth2:
    client:
      clientId: XXXXXX
      clientSecret: XXXXXXX
      accessTokenUri:  https://www.googleapis.com/oauth2/v3/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form 
    resource:
      userInfoUri: https://www.googleapis.com/userinfo/v2/me